# Default values for oauth-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/choerodon/oauth-server
  pullPolicy: Always

preJob:
  timeout: 300
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  preConfig:
    enable: true
    configFile: application.yml
    configType: k8s
    registerHost: http://register-server:8000
    datasource:
      url: jdbc:mysql://localhost:3306/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: username
      password: password

deployment:
  managementPort: 8021

metrics:
  path: /actuator/prometheus
  group: spring-boot

logs:
  parser: spring-boot

env:
  open:
    SPRING_CLOUD_CONFIG_ENABLED: true
    SPRING_CLOUD_CONFIG_URI: http://register-server.io-choerodon:8000
    SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1/event_store_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: username
    SPRING_DATASOURCE_PASSWORD: password
    SPRING_REDIS_HOST: localhost
    SPRING_REDIS_PORT: 6379
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://register-server.io-choerodon:8000/eureka/
    CHOERODON_DEFAULT_REDIRECT_URL: localhost:8080/manager/swagger-ui.html
    CHOERODON_OAUTH_LOGIN_PATH: /loginactuator
    CHOERODON_OAUTH_LOGIN_SSL: false
    # skywalking 代理端配置
    #    SKYWALKING_OPTS: >-
    #      -javaagent:/agent/skywalking-agent.jar
    #      -Dskywalking.agent.application_code=oauth-server
    #      -Dskywalking.agent.sample_n_per_3_secs=-1
    #      -Dskywalking.collector.backend_service=oap.skywalking:11800

service:
  enable: false
  type: ClusterIP
  port: 8020
  name: oauth-server

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 2Gi
  requests:
    # cpu: 100m
    memory: 1Gi